[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vrf_sol = "A4pDDsKvtX2U3jyEURVSoH15Mx4JcgUiSqCKxqWE3N48"
roll_dice = "7Q5b9aimnHmR8ooooRqxgfYfnLmPi6qrVR9GrJ1b6fDp"

[programs.devnet]
vrf_sol = "A4pDDsKvtX2U3jyEURVSoH15Mx4JcgUiSqCKxqWE3N48"
roll_dice = "7Q5b9aimnHmR8ooooRqxgfYfnLmPi6qrVR9GrJ1b6fDp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://devnet.helius-rpc.com/?api-key=e26bf879-6bb4-49c0-aafa-8e4d86687455"
wallet = "~/.config/solana/testnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
